### ISSUE TITLE
Allow for ability to handle godot `InputEvent`s

### ISSUE THREAD

**Issue by jrockett6** [rand0m-cloud/bevy_godot#13]
Hi, I wasn't able to find an nice way to get access to godot `InputEvent` handles that are normally passed via `_input` or `_unhandled_input` in nodes. I went ahead and made a very rough draft (partly as a learning exercise for myself) of getting these into bevy events here: https://github.com/jrockett6/bevy_godot/tree/godot-input-to-bevy-events

If there already exists a good way to get access to `InputEvent` information I'd be curious to hear. Otherwise I'd be happy to open up a PR with the above changes and incorporate any feedback (I'm very new to the rust/godot/bevy ecosystem). 

Thanks very much for your awesome library!

**Comment by rand0m-cloud** [comment]
Hello, thank you for your interest! I thought you could get mouse motion from the `Input` class but that's not so. 

Please open a PR for this!

**Comment by rand0m-cloud** [comment]
Closed by #14
